// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9L7AXBhVSSD7c1sqSF-ULY1Mvp8M8b8A',
    appId: '1:393345333403:web:42b11795e1169376a82e3e',
    messagingSenderId: '393345333403',
    projectId: 'lus-app-bd8f0',
    authDomain: 'lus-app-bd8f0.firebaseapp.com',
    storageBucket: 'lus-app-bd8f0.appspot.com',
    measurementId: 'G-7YLDN41HVL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD04noY-EpaSAVlyK5kNTj50lpWGg5UMfY',
    appId: '1:393345333403:ios:bf2c460095b4a208a82e3e',
    messagingSenderId: '393345333403',
    projectId: 'lus-app-bd8f0',
    storageBucket: 'lus-app-bd8f0.appspot.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD04noY-EpaSAVlyK5kNTj50lpWGg5UMfY',
    appId: '1:393345333403:ios:bf2c460095b4a208a82e3e',
    messagingSenderId: '393345333403',
    projectId: 'lus-app-bd8f0',
    storageBucket: 'lus-app-bd8f0.appspot.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9L7AXBhVSSD7c1sqSF-ULY1Mvp8M8b8A',
    appId: '1:393345333403:web:0c6db0d0509b3d66a82e3e',
    messagingSenderId: '393345333403',
    projectId: 'lus-app-bd8f0',
    authDomain: 'lus-app-bd8f0.firebaseapp.com',
    storageBucket: 'lus-app-bd8f0.appspot.com',
    measurementId: 'G-T4YMEF5PFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUi5gSo4orUnj7yQswLSDjmW39rE9mcnI',
    appId: '1:393345333403:android:2493a4b66d9f339fa82e3e',
    messagingSenderId: '393345333403',
    projectId: 'lus-app-bd8f0',
    storageBucket: 'lus-app-bd8f0.appspot.com',
  );

}